### ISSUE TITLE
parse_semester should give help if year is too early

### ISSUE THREAD

**Issue by jyn514** [jyn514/GradeForge#17]
`parse_semester` currently gives a *very* unhelpful error if given a year before 2013. Since 2008-2012 *are* valid for grades, it should at a minimum say why it's rejected the year.

The current output:
```
>>> gradeforge.utils.parse_semester('201208')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joshua/Documents/Programming/Python/gradeforge/gradeforge/utils.py", line 147, in parse_semester
    raise ValueError("'%s' not a valid USC season for year %s" % (season, year))
ValueError: '201208' not a valid USC season for year 2018
```

What it should do:
if the current check for `allowed` fails, see if it's in the proper format. if so, parse the year and say if it's too early, too late, or just weird.

**Comment by jyn514** [comment]
I should also go back and look at `allowed` at some point. There's a lot of QOL things that have been put on the backburner until the project is semi-working.
